= Pin Library for Arduino =

This library allows to transform the digital and analogue ports into objects and to allow in a simpler way to work with PWM, bouncing effect, standardized method of reading and writing, independent if the ports is digital or analogic.

Available methods:

    void setToDigital(); // Somente se quiser usar uma porta analogica como digital
    void setMode(byte); // (0) INPUT, (1) OUTPUT, (2) INPUT_PULLUP
    void setDebounceDelay(unsigned long); // Tempo de debounce. Default is 50 ms
    int read(); // digitalRead 0 - 1 ou analogRead 0 - 500
    bool readWithDebounce(); // digitalRead com debounce
    void write(bool); // digitalWrite 0 ou 1
    void writePwm(int); // analogWrite 0 - 500

For more information about this library please visit us at
https://github.com/silviogarbes/Arduino-Pin

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
